name: Deploy WordPress with Terraform

on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write' # Needed for Workload Identity Federation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud via WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wp-app/wordpress:latest -f "Task 3/Dockerfile" "Task 3"


      - name: Push image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wp-app/wordpress:latest

      - name: Set IMAGE_URI env variable
        run: echo "IMAGE_URI=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/wp-app/wordpress:latest" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./Task\ 3/GCP
        run: terraform init

      - name: Terraform Plan
        working-directory: ./Task\ 3/GCP
        run: terraform plan -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="image_uri=$IMAGE_URI"

      - name: Terraform Apply
        working-directory: ./Task\ 3/GCP
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="image_uri=$IMAGE_URI"
